SpectraLogic/ds3_autogen

- ds3-autogen-net/src/main/resources/tmpls/net/request/common/optional_checksum.ftl
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetCodeGenerator_Test.java
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/utils/TestHelper.java
The checksum type object being named Type was creating warnings as it conflicts with other elements that can be named type in net sdk. Renaming the checksum type removed 17 warnings in net sdk.
> Modified checksumtype.type name to avoid naming conflicts

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/ResponseParserGeneratorUtil.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/helpers/JavaHelper.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/ResponseCode.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/ResponseParser.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/BaseParseResponse.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/EmptyParseResponse.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/ParseResponse.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/StringParseResponse.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/response_parser_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/parseresponse/ParseResponse_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/ResponseParserGeneratorTestUtil.java
**Changes**
- Copied parsing logic from response generator to response parser generator
- Refactored parsing logic to use new ResponseCode model instead of contract Ds3ResponseCode within template
- Refactored parsing logic from java helper to utility files and ResponeParserGenerator to clean up template files
- Special case response parsers
- Update response handlers to simple POJOs
> Parsing code implemented in BaseResponseParser in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/CodesResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtils.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/CodesResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/test/helpers/Ds3ResponseCodeFixtureTestHelper.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtil_Test.java
**Goal**
Separate Response Handlers into Response Handlers (simple POJOs) and Response Parsers in java module
**Changes**
- Special cased Head Bucket response parser
- Moved getResponseCodes from Response Generator into utility
- Moved associated tests
- Special case remaining response parsers
- Change response handlers to simple POJOs
- Special case Head Bucket response handler
- Add enum Status
- Add Status parameter
--
--
```
/* …
```
> Special cased head bucket response parser in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/head_object_response_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
**Goal**
Separate Response Handlers into Response Handlers (simple POJOs) and Response Parsers in java module
**Changes**
Special cased Head Object response parser
- Special case remaining response parsers
- Change response handlers to simple POJOs
- Special case Head Object response handler
- Add enum Status
- Add parameters: status, metadata, and objectSize
--
Generated Code
--
```
/*
*
*
*   or in the …
```
> Special cased Head Object response parser in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/allocate_job_chunk_response_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
**Goal**
Separate Response Handlers into Response Handlers (simple POJOs) and Response Parsers in java module
**Changes**
- Special cased Allocate Job Chunks response parser
- Created function getResponseModelName in BaseResponseParserGenerator to reuse code
- Special case remaining response parsers
- Change response handlers to simple POJOs
- special case Allocate Job Chunk response handler
- Add enum status
- Add parameters: objectsResult, retryAfterSeconds, and status
--
Generated Code
--
```
/*
*   this file except in compliance with …
```
> Special cased Allocate Job Chunk response handler in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtils.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/common/parse_retry_after.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_job_chunks_ready_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtil_Test.java
- ds3-autogen-java/src/test/resources/input/getJobChunksReadyForClientProcessingRequest.xml
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
**Changes**
- Special cased GetJobChunksReadyForClientProcessing response parser
- Moved getDs3ResponseCode from generator into utility function
- Placed parseRetryAfter java code in separate template for re-usability
- Updated test input file GetJobChunksReadyForClientProcessing to 3.2.2 version
- Special case get object response parser
- Change response handlers to simple POJOs
- Special case GetJobChunksReadyForClientProcessing response handler
- Add Status enum
- Add vars: masterObjectListResult, status, retryAfterSeconds
--
Generated Code
--
```
/*
*   Licensed under the Apache License, Version 2.0 (the "License"). …
```
> Special cased GetJobChunksReadyForClientProcessing response parser

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/NullParseResponse.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/parseresponse/ParseResponse_Test.java
**Changes**
- Added parser testing to rest of functional tests
- Fixed bug in parser generation: when there are multiple non-error response codes and one returns the payload and one does not, incorrect return was generated.
- was: `return ExampleResponse()`
- now: `return ExampleResponse(null)`
- Special case response handlers
- Code cleanup (address all remaining TODOs)
> Improved functional testing of response parsers and fixed bug

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/response/head_object_response.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator_Test.java
**Changes**
- Special cased Head Object response handler
- Fixed bug in base response generator where parent import was not included if Ds3ResponseCodes was empty/null
- Special case additional response handlers as needed
- Code cleanup
--
Generated Code: HeadObjectResponse.java
--
```
/*
*
*
*   This file is distributed on an "AS IS" BASIS, WITHOUT …
```
> Special cased head object response handler in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadBucketResponseGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/response/common/constructor_and_params.ftl
- ds3-autogen-java/src/main/resources/tmpls/response/head_bucket_response.ftl
- ds3-autogen-java/src/main/resources/tmpls/response/head_object_response.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadBucketResponseGenerator_Test.java
**Changes**
- Special cased Head Bucket response handler
- Placed common response template code into separate file for re-use
- Special case response handlers as needed
- Update client impl to match new format
- Code cleanup
--
Generated Code: HeadBucketResponse.java
--
```
/*
*
*
*   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR …
```
> Special cased Head Bucket response handler in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BulkResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/ResponseGeneratorUtil.java
- ds3-autogen-java/src/main/resources/tmpls/response/bulk_response.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BulkResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
- ds3-autogen-java/src/test/resources/input/createGetJobRequestHandler.xml
- ds3-autogen-java/src/test/resources/input/createPutJobRequestHandler.xml
**Changes**
- Special cased bulk response handler generation
- Updated test input files to BP 3.2.2 for Bulk Put and Bulk Get commands
- Renamed JavaCodeGenerator functions for clarity
- getResponseTemplateModelGenerator -> getResponseGenerator
- getTemplateModelGenerator -> getRequestGenerator
- Removed unused parameters in response generator methods
- getParentClass
- getParentImport
- Special case Get Object response handler generation
- Update ClientImpl generation
- Code cleanup
--
Generated Code: Bulk Get Response handler
--
```
/* …
```
> Special cased bulk response handler generation in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/GetObjectResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/ResponseGeneratorUtil.java
- ds3-autogen-java/src/main/resources/tmpls/response/get_object_response.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/GetObjectResponseGenerator_Test.java
**Changes**
- Special cased Get Object response handler
- Defined `toConstructorParams` in `ResponseGeneratorUtil` interface so it can be overloaded within response generators
- Update ClientImpl generation
- Code cleanup
--
Generated Code: GetObjectResponse.java
--
```
/*
*
*
*   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
* …
```
> Special cased Get Object response handler generation in java module

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/helpers/JavaHelper.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtils.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/helpers/JavaHelper_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/ResponseAndParserUtil_Test.java
**Changes**
- Deleted all unused `JavaHelper` methods and associated tests
- Moved `convertType` method implementation to `ResponseAndParserUtils` and created wrapper for it in `JavaHelper` to reduce coupling since it is used in both templates and within code generators
> Cleaned up java module code

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/client/ds3client_impl_template.ftl
- ds3-autogen-java/src/main/resources/tmpls/response/common/constructor_and_params.ftl
- ds3-autogen-java/src/main/resources/tmpls/response/get_object_response.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/allocate_job_chunk_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/bulk_response_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_job_chunks_ready_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/head_object_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/response_parser_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
**Changes**
- Specified response handler in response parsers when referencing a Status enum defined in the response handler: 
- was `Status.ENUM_STATUS`, now `ResponseHandler.Status.ENUM_STATUS`
- Added import of parsers package in Ds3ClientImpl
- Removed erroneous `this` reference in constructor assignments
- Fixed getter function names from parent class
- headers -> getHeaders
- statusCode -> getStatusCode
> Minor bug fixes in java generated code

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/PaginationResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/ResponseGeneratorUtil.java
- ds3-autogen-java/src/main/resources/tmpls/response/pagination_response.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/PaginationResponseGenerator_Test.java
**Changes**
- Moved pagination header logic to new Pagination Response Generator and template
- Response handlers that have pagination headers now extend AbstractPaginationResponse
--
Example Generated Code: GetBucketsSpectraS3Response.java
--
```
/*
*
*
*   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
*   CONDITIONS OF ANY KIND, either express or …
```
> Moved pagination headers to separate response generator

- ds3-autogen-api/src/main/java/com/spectralogic/ds3autogen/api/models/apispec/Ds3Element.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/CCodeGenerator.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/StructConverter.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/EnumHelper.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Struct.java
- ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
- ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java
- ds3-autogen-c/src/test/resources/input/3_2_2_contract.xml
- ds3-autogen-parser/src/main/resources/typeNameMap.json
Eliminate most of the ~100 build warnings about defined but unused methods.
Fix Ds3Element equals comparison to handle properties that are null (ComponentType)
Special case TargetReadPreference to TargetReadPreferenceType to avoid conflict with Ds3TargetReadPreference response type.
Improve filtering of array types
* Example:
*      <Ds3Targets>
<Ds3Target>
<AccessControlReplication>NONE</AccessControlReplication>
<AdminAuthId>aid</AdminAuthId>
<AdminSecretKey>ask</AdminSecretKey>
<DataPathEndPoint>dp</DataPathEndPoint>
<DataPathHttps>true</DataPathHttps>
<DataPathPort />
<DataPathProxy />
<DataPathVerifyCertificate>true</DataPathVerifyCertificate>
<DefaultReadPreference>LAST_RESORT</DefaultReadPreference>
<Id>02a0faf9-c5c7-4b47-b4e0-29c4d2906f90</Id>
<Name>ds3t2</Name> …
> Build warnings

- ds3-autogen-java/src/main/resources/tmpls/copyright.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
All java generated code now has the updated copyright dates 2014-2016
> Updated copyright dates in java template

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_object_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator_Test.java
**Changes**
Updates the generation of GetObjectParser to use the existing SDK networking code instead of the new networking code (which uses futures)
> Changes Get Object Parser generation to use the old networking code format

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/BaseParseResponse.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/StringParseResponse.java
- ds3-autogen-java/src/main/resources/tmpls/responseparser/allocate_job_chunk_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/bulk_response_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_job_chunks_ready_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_object_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/head_object_parser.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/response_parser_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/parseresponse/ParseResponse_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
**Changes**
Removed BlockingByteChannel in the response parsers as this is only used with the new networking code, and is not supported with the current networking code.
> Removed blockingByteChannel from response parser generation

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/converters/ClientConverter.java
- ds3-autogen-java/src/main/resources/tmpls/client/ds3client_impl_template.ftl
- ds3-autogen-java/src/main/resources/tmpls/responseparser/get_object_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/converters/ClientConverter_Test.java
**Changes**
- Renamed parser function `startResponse` to `response` for clarity
- Added missing import in GetObjectResponseParser template
> Java refactor cleanup

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/requestmodels/GetObjectRequestGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/request/get_object_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/requestmodels/GetObjectRequestGenerator_Test.java
**Changes**
- Added generation of a constructor that accepts an OutputStream and internally converts it to a channel for `GetObjectRequest` handler in java module
- Since the `channel` variable is not required for all constructors, the implementation of `toConstructorArgumentsList` was removed and replaced with `toClassVariableArguments` which guarantees that the `channel` var exists within the generated class and has a getter function.
---
Generated Code: GetObjectRequest.java
---
```
/*
*   this file except in compliance with the License. A copy of the …
```
> Added OutputStream constructor for GetObjectRequest handler in java module

- ds3-autogen-cli/build.gradle
- ds3-autogen-cli/src/main/java/com/spectralogic/autogen/cli/GeneratorType.java
- ds3-autogen-cli/src/main/java/com/spectralogic/autogen/cli/Main.java
- ds3-autogen-python/build.gradle
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/PutObjectRequestGenerator.java
- ds3-autogen-python/src/main/kotlin/com/spectralogic/ds3autogen/python/PythonCodeGeneratorInterface.kt
- ds3-autogen-python/src/main/resources/tmpls/python/commands/create_client.ftl
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
- ds3-autogen-python3/build.gradle
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/Python3CodeGenerator.kt
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/generators/request/P3PutObjectRequestGenerator.kt
- ds3-autogen-python3/src/main/resources/tmpls/python3/commands/p3_all_commands.ftl
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/Python3FunctionalTests.java
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/request/P3PutObjectRequestGenerator_Test.java
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/utils/TestPython3GeneratedCode.java
- ds3-autogen-python3/src/test/resources/input/requests/putObject.xml
- ds3-autogen-python3/src/test/resources/input/requests/simpleRequest.xml
- settings.gradle
**Changes**
- Added cli option for `PYTHON3`
- Added Python3 module which depends on Python module
- Updated static code in Templates:
- Updated `AbstractRequest` constructor for specifying metaclass
- Updated `AbstractResponse` constructor for specifying metaclass
- Updated import to `from .ds3network import *` from `from ds3network import *`
- Updated request generator:
- Updated `GetObjectRequest` generation to iterate through lists with `headers.items()` vs `headers.iteritems()`
> Generate Python3 module

- ds3-autogen-cli/src/main/java/com/spectralogic/autogen/cli/CLI.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Guards.java
This was done so that the util can be reused within the contract comparator project.
> Moved Guards from cli module to utils module

- ds3-autogen-java/src/main/resources/tmpls/request/create_object_template.ftl
The Java SDK file PutObjectRequest was manually modified to make metadata keys' lower case. This updates the associated template within autogen to preserve this change.
> Updating Java PutObjectRequest template 

- build.gradle
- ds3-autogen-api/src/main/java/com/spectralogic/ds3autogen/api/models/Arguments.java
- ds3-autogen-api/src/main/kotlin/com/spectralogic/ds3autogen/api/models/Arguments.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestModelGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/request/Constructor.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/request/Request.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/request/Variable.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/request/WithConstructor.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/utils/GoTypeUtil.kt
- ds3-autogen-go/src/main/resources/tmpls/request/request_template.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTestCodeUtil.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTypeUtil_Test.java
- ds3-autogen-go/src/test/resources/input/requestWithResourceInPath.xml
- ds3-autogen-go/src/test/resources/input/simpleRequestWithPayload.xml
**Changes**
- Implemented `BaseRequestGenerator`
- Updated/created request models used in template
- Update request handler template
> SA 173- Generation of non-special-cased Go request handlers

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestPayloadGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/StringRequestPayloadGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequiredObjectsPayloadGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/StringRequestPayloadGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/replicatePutJob.xml
**Changes**
- Created Go request generator for commands with request payloads of type `string`
- Moved request payload logic from `RequiredObjectsPayloadGenerator` into abstract `RequestPayloadGenerator` for code reusability
> Go generation of requests with string payloads

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/getJobToReplicate.xml
**Changes**
- Updated response generation to handle string payloads
Note: the code that this generates for string payload responses has already been approved in Go SDK review https://github.com/SpectraLogic/ds3_go_sdk/pull/19
> Fixed improper handling of responses with string payloads in go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/type/BaseTypeGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/type/Type.kt
- ds3-autogen-go/src/main/resources/tmpls/go/type/enum_type.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/type/BaseTypeGenerator_Test.java
Generated enums have name collisions. This name spaces the enum values with the type name as a prefix.
Example code of generated enum:
```
package models
import (
"errors"
"fmt"
"bytes"
)
type DatabasePhysicalSpaceState Enum
const (
DATABASE_PHYSICAL_SPACE_STATE_CRITICAL DatabasePhysicalSpaceState = 1 + iota
DATABASE_PHYSICAL_SPACE_STATE_LOW DatabasePhysicalSpaceState = 1 + iota
DATABASE_PHYSICAL_SPACE_STATE_NEAR_LOW DatabasePhysicalSpaceState = 1 + iota
DATABASE_PHYSICAL_SPACE_STATE_NORMAL DatabasePhysicalSpaceState = 1 + iota
)
func (databasePhysicalSpaceState *DatabasePhysicalSpaceState) UnmarshalText(text []byte) error {
var str string = string(bytes.ToUpper(text))
switch str {
case "CRITICAL": *databasePhysicalSpaceState = DATABASE_PHYSICAL_SPACE_STATE_CRITICAL
case "LOW": …
```
> Name spaced enum values with type names

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
Fixed bug where a string pointer was not being dereferenced properly when accessing string value in Go generated code
Old: `strPtr.String()`
New: `*strPtr`
> Fixed error in converting a string pointer into a string

- ds3-autogen-go/src/main/resources/tmpls/go/type/enum_type.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
Example enum generated code: 
```
package models
import (
"errors"
"fmt"
"bytes"
"log"
)
type Priority Enum
const (
PRIORITY_CRITICAL Priority = 1 + iota
PRIORITY_URGENT Priority = 1 + iota
PRIORITY_HIGH Priority = 1 + iota
PRIORITY_NORMAL Priority = 1 + iota
PRIORITY_LOW Priority = 1 + iota
PRIORITY_BACKGROUND Priority = 1 + iota
)
func (priority *Priority) UnmarshalText(text []byte) error {
var str string = string(bytes.ToUpper(text))
switch str {
case "CRITICAL": *priority = PRIORITY_CRITICAL
case "URGENT": *priority = PRIORITY_URGENT
case "HIGH": *priority = PRIORITY_HIGH
case "NORMAL": *priority = PRIORITY_NORMAL
case "LOW": *priority = PRIORITY_LOW
case "BACKGROUND": *priority = PRIORITY_BACKGROUND
default:
*priority = UNDEFINED
return errors.New(fmt.Sprintf("Cannot marshal '%s' …
```
> Changed Go enum-to-string to log error rather than return error

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/GetObjectRequestGenerator.kt
- ds3-autogen-go/src/main/resources/tmpls/go/request/get_object_request.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/no_checksum.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/no_headers.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/request_body.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/request_header.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/request_template.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/request_with_stream.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/stream_no_content.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/stream_with_content.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/request/with_checksum.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/GetObjectRequestGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/getObject.xml
**Changes**
- Created template and request generator for Get Object command
- Pulled some logic out of overloaded functions in `BaseRequestGenerator` for re-usability
- Separated request template logic into multiple new templates for re-usability
Generated Code:
```
package models
import (
"fmt"
"net/url"
"net/http"
"strconv"
)
type rangeHeader struct {
start, end int
}
type GetObjectRequest struct {
objectName string
checksum networking.Checksum
job string
offset int64
rangeHeader *rangeHeader
}
func NewGetObjectRequest(bucketName string, objectName string) *GetObjectRequest {
return &GetObjectRequest{
bucketName: bucketName,
objectName: objectName,
checksum: networking.NewNoneChecksum(),
queryParams: …
```
> Special cased amazon Get Object request in Go

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/utils/GoNamingUtil.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoNamingUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTestCodeUtil.java
- ds3-autogen-go/src/test/resources/input/getAzureDataReplicationRules.xml
- ds3-autogen-go/src/test/resources/input/putAzureDataReplicationRule.xml
There was a conflict in generated request parameters of name `type` since this is a keyword in Go.  This creates a `toGoParamName` util which renames parameters `type` to use their classes.  Parameters that are lists are namespaced to include List in their name.
Example name changes:
`type PoolType` -> `poolType PoolType`
`type []PoolType` -> `poolTypeList []PoolType`
> Namespaced parameters called 'Type' to use spectra type names

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestPayloadGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
- ds3-autogen-go/src/test/resources/input/deleteJobCreatedNotificationRegistration.xml
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/RequestConverterUtil.java
The generation of notification requests was not correctly generating notification IDs when required. This is caused by some incorrect assumptions in autogen utils which all modules use. For the Go implementation of notification request handlers, a new "Go" version of the utilities was created to convert any notification type resource that is included-in-path into the argument `notificationId`.  Updating the autogen util may be done at a later time, but will have cascading effects on multiple modules.
**Changes**
- Fixed generation of notification request handlers with a `notificationId`
- Refactored some redundant code within request generators to maximize code reuse.
> Fixed notification resource generation in Go request handlers

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/PartsRequestPayloadGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/ReaderRequestPayloadGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/ReaderRequestPayloadGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/putMultiPartUploadPart.xml
**Changes**
- Renamed `MultipartUploadPayloadGenerator` -> `PartsRequestPayloadGenerator` to remove confusion regarding the different special casing for `CreateMultiPartUploadRequest` and `CompleteMultiPartUploadRequest`
- Created `ReaderRequestPayloadGenerator` to special case PutMultiPartUpload request which has a request payload of type `ReaderWithSizeDecorator`
> Special cased PutMultiPartUpload request

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/ReaderRequestPayloadGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/response/Response.kt
- ds3-autogen-go/src/main/resources/tmpls/go/response/response_template.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/simpleRequestNoPayload.xml
Generated code:
```
package models
import (
"io"
)
type GetObjectResponse struct {
Content io.ReadCloser
}
func NewGetObjectResponse(webResponse networking.WebResponse) (*GetObjectResponse, error) {
expectedStatusCodes := []int { 200, 206 }
switch code := webResponse.StatusCode(); code {
case 200:
return &GetObjectResponse{ Content: webResponse.Body() }, nil
case 206:
return &GetObjectResponse{}, nil
default:
return nil, buildBadStatusCodeError(webResponse, expectedStatusCodes)
}
}
```
> Special cased Go generation of Amazon Get Object response handler

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTestCodeUtil.java
**Changes**
- Request handlers, response handlers, and types are now generated with the first character lower-cased.  Before, there was an oversight were only the clients were being generated correctly.
- Updated some Go functional tests that were throwing null pointer exception errors due to incorrectly assuming some test scenarios were not generating types.  These exceptions were being swallowed and not interfering with the tests, but printed stack-traces were pointlessly cluttering up the output.
> Updated Go generation to generate files with lower cased names

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/generators/response/ResponseModelGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/NoResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/ResponseModelGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/response/Response.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/NoResponseGenerator_Test.java
**Changes**
Discovered that the response parsing function starts parsing from one xml tag within (i.e. the outer-most tag is ignored).  Therefore, I updated the response handlers to not specify xml parsing for the highest level tag, and now the response payload is passed into the parsing function, and not the response handler (which contains the response payload).
**Tests**
This update makes 5 additional Go unit tests pass (all those with response payloads that are not failing due to unrelated errors).
```
package models
import (
)
type GetServiceResponse struct {
ListAllMyBucketsResult ListAllMyBucketsResult
}
func NewGetServiceResponse(webResponse networking.WebResponse) (*GetServiceResponse, error) {
expectedStatusCodes := []int { 200 }
switch code := …
```
> Fixed generation of Go response handlers

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/type/BaseTypeGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/type/BaseTypeGenerator_Test.java
**Changes**
Go response types now generating with xml parsing assuming capitalized tag names.
**Tests**
This fixes the last 2 broken unit tests in the Go SDK.
Originally the ID variable was generated as `Id string 'xml:"iD"'`
```
package models
type User struct {
DisplayName *string `xml:"DisplayName"`
Id string `xml:"ID"`
}
```
> Go response models now generating with captilazed tag names

- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/RequestConverterUtil.java
**Changes**
- Updated DATA_PERSISTENCE_RULE to be treated as an ID (i.e. UUID or Guid) and not as a string
- The effects of this update have already been approved and merged in the Net SDK https://github.com/SpectraLogic/ds3_net_sdk/pull/257#discussion_r118050948
- A java test was failing due to line ending differences when run on windows. Updated test to use a pattern rather than matching a string.
> Update resource from string to UUID, and fixed java test

- ds3-autogen-go/src/main/resources/tmpls/go/type/enum_type.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
```
package models
import (
"errors"
"fmt"
"bytes"
"log"
)
type Priority Enum
const (
PRIORITY_CRITICAL Priority = 1 + iota
PRIORITY_URGENT Priority = 1 + iota
PRIORITY_HIGH Priority = 1 + iota
PRIORITY_NORMAL Priority = 1 + iota
PRIORITY_LOW Priority = 1 + iota
PRIORITY_BACKGROUND Priority = 1 + iota
)
func (priority *Priority) UnmarshalText(text []byte) error {
var str string = string(bytes.ToUpper(text))
switch str {
case "": *priority = UNDEFINED
case "CRITICAL": *priority = PRIORITY_CRITICAL
case "URGENT": *priority = PRIORITY_URGENT
case "HIGH": *priority = PRIORITY_HIGH
case "NORMAL": *priority = PRIORITY_NORMAL
case "LOW": *priority = PRIORITY_LOW
case "BACKGROUND": *priority = PRIORITY_BACKGROUND
default:
*priority = UNDEFINED
return …
```
> Updating go enum generation to set UNDEFINED as default value

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator.kt
- ds3-autogen-go/src/main/resources/tmpls/go/response/response_template.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator_Test.java
**Changes**
Added response header to response struct and propagated with web response headers.
```
package models
import (
"net/http"
)
type GetServiceResponse struct {
ListAllMyBucketsResult ListAllMyBucketsResult
Headers *http.Header
}
func NewGetServiceResponse(webResponse networking.WebResponse) (*GetServiceResponse, error) {
expectedStatusCodes := []int { 200 }
switch code := webResponse.StatusCode(); code {
case 200:
var body GetServiceResponse
if err := readResponseBody(webResponse, &body.ListAllMyBucketsResult); err != nil {
}
body.Headers = webResponse.Header()
return &body, nil
default:
return nil, buildBadStatusCodeError(webResponse, expectedStatusCodes)
}
}
```
> Added headers to Go response handler generation

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/QueryParam.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/QueryParam_Test.java
**Changes**
Updates java request generation to use percent encoding method for query params. The code generated by this change has been merged into the SDK in PR https://github.com/SpectraLogic/ds3_java_sdk/pull/475
> SDKPM-33: Update java module to generate requests with percent encoded query params

- ds3-autogen-java/src/main/resources/tmpls/java/client/ds3client_impl_template.ftl
- ds3-autogen-java/src/main/resources/tmpls/java/client/ds3client_template.ftl
Generates code that has already been merged into java SDK in PRs:
https://github.com/SpectraLogic/ds3_java_sdk/pull/483
https://github.com/SpectraLogic/ds3_java_sdk/pull/485
> Updating java client templates for JSDK-242 fix

- ds3-autogen-c/src/main/resources/templates/source-templates/ds3_init_requests.ftl
- ds3-autogen-c/src/main/resources/templates/source-templates/ds3_requests.ftl
- ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
- ds3-autogen-c/src/main/resources/templates/source-templates/modify_request.ftl
update templates to current c sdk match after https://github.com/SpectraLogic/ds3_c_sdk/pull/205
> Update C SDK string buffers

- .gitignore
- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/generators/parser/TypeParserModelGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/TypeParserGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseAttributeImpls.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseElement.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/TypeParser.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/utils/GoFormattingUtil.kt
- ds3-autogen-go/src/main/resources/tmpls/go/parser/base_type_parser.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/parser/type_parser_with_list.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseAttributeImpls_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParserAttributeImpls_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoFormattingUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoModelFixturesUtil.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTestCodeUtil.java
- ds3-autogen-go/src/test/resources/input/getTypesParsedAsSliceTestInput.xml
- ds3-autogen-go/src/test/resources/input/simpleType.xml
**Changes**
- Added `out/` folder to gradle ignore
- Added model parser generation for all non-enum types defined within the contract.
- Need to special case model parsers as necessary
- Need to update response handlers to use new parsing method
- Need to simplify model generation to remove unused xml parsing notation
**Example Generated Code**
```
package models
func (job *Job) parse(node *XmlNode, aggErr *AggregateError) {
// Parse Attributes
for _, attr := range node.Attrs {
switch attr.Name.Local {
case "Aggregating":
job.Aggregating = parseBoolFromString(attr.Value, aggErr)
case "BucketName":
job.BucketName = parseNullableStringFromString(attr.Value)
case "CachedSizeInBytes":
job.CachedSizeInBytes = parseInt64FromString(attr.Value, aggErr)
case …
```
> SA-183: implement custom Go parsing of payloads

- ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/utils/GeneratorUtils.java
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/utils/GeneratorUtils_Test.java
The code that this update generates was merged to the Net SDK in PR https://github.com/SpectraLogic/ds3_net_sdk/pull/265
> SA-182: Net request handler paths no longer conver string represented Guids to string

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/response/Response.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/utils/GoFormattingUtil.kt
- ds3-autogen-go/src/main/resources/tmpls/go/parser/base_type_parser.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/parser/parser_body.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/parser/type_parser_with_list.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/response/response_template.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoFormattingUtil_Test.java
**Changes**
- Updated generation of Go response handlers to use the new parsing method.
- Added a `parse` method to response handlers when response payload is of a Ds3Type
- Fixed load template error caused by incorrect file name.
- Namespaced Go module's `indent` util to `goIndent` to remove conflict with `helper.indent`
- Readjusted type model templates for better code reuse and to add in a required import
- Fix bug in model parser generation where lists of enums are not parsed correctly
- Remove unnecessary logic from model generation related to unused xml notation
**Example Generated Code**
```
package models
import (
"net/http"
)
type GetJobsSpectraS3Response struct {
JobList JobList
Headers *http.Header
}
func (getJobsSpectraS3Response …
```
> SA-183 continued: Updated Go response handlers to use new parsing method

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoModelFixturesUtil.java
**Changes**
- Slices of enums were being parsed incorrectly in generated parser code. This fix removes the last of the compilation errors in Go SDK.
**Sample Code**
See `TapeTypes` and `DriveTypes` in switch for updated code.
```
package models
func (detailedTapePartition *DetailedTapePartition) parse(xmlNode *XmlNode, aggErr *AggregateError) {
// Parse Child Nodes
for _, child := range xmlNode.Children {
switch child.XMLName.Local {
case "DriveType":
parseNullableEnum(child.Content, detailedTapePartition.DriveType, aggErr)
case "DriveTypes":
var model TapeDriveType
parseEnum(child.Content, &model, aggErr)
detailedTapePartition.DriveTypes = append(detailedTapePartition.DriveTypes, model)
case "ErrorMessage":
detailedTapePartition.ErrorMessage = parseNullableString(child.Content)
case …
```
> SA-185: Fixed Go parsing of enum slices

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/JobListParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/TypeParserGeneratorUtil.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/JobListParserGenerator_Test.java
With this change, all integration and unit tests in the Go SDK pass.
```
package models
func (jobList *JobList) parse(xmlNode *XmlNode, aggErr *AggregateError) {
// Parse Child Nodes
for _, child := range xmlNode.Children {
switch child.XMLName.Local {
case "Job":
var model Job
model.parse(&child, aggErr)
jobList.Jobs = append(jobList.Jobs, model)
}
}
}
```
> SA-186: Special cased Go JobList parser

- build.gradle
- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/JobListParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/BaseResponseGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/type/BaseTypeGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/type/JobListGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoTestCodeUtil.java
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/logging/GeneratedCodeLogger.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Helper.java
- ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Helper_Test.java
**Changes**
Replaced Java StringUtils implementation of capitalize and uncapitalize strings with Kotlin build in string extension methods. This was done for code cleanup.  Instances of cap/uncap were also replaced within Java code for consistency.
- Replaced `StringUtils.capitalize` with `StringsKt.capitalize`
- Replaced `StringUtils.uncapitalize` with `StringsKt.decapitalize`
Added unit tests to `Helper.uncap` and `Helper.cap` as sanity check due to change of library implementation.
> Changed from using StringUtils cap and uncap to using kotlin cap and decap

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoModelFixturesUtil.java
- ds3-autogen-go/src/test/resources/input/listBucketResult.xml
**Changes**
- Special cased the parsing code for the CommonPrefixes Ds3Element
- Added unit and functional tests
Generated code was merged to Go SDK in PR: https://github.com/SpectraLogic/ds3_go_sdk/pull/27
> SA-189: Fixing generated parsing code for handling common prefixes in Go

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/requestmodels/IdsRequestPayloadGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/java/request/ids_request_payload_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/resources/input/clearSuspectBlobAzureTargetsSpectraS3Request.xml
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
- ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java
**Changes**
- Added util `hasIdsRequestPayload` to determine if a Ds3Request accepts a payload of Ids
- Special cased Ds3Requests in the Java module for taking in the ids request payload
- Generated code can be found in https://github.com/SpectraLogic/ds3_java_sdk/pull/489
> SA-193: Added util for determining Ids request payload and special cased in Java module

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/IdsPayloadRequestGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/IdsPayloadRequestGenerator_Test.java
- ds3-autogen-go/src/test/resources/input/clearSuspectBlobAzureTargetsSpectraS3.xml
**Changes**
- Special cased generated Go request handlers with payload of ids to take in `ids []string` and convert it into proper xml payload using utility `buildIdListPayload`
**Sample Generated Code**
```
package models
import (
"net/url"
"net/http"
)
type ClearSuspectBlobAzureTargetsSpectraS3Request struct {
}
func NewClearSuspectBlobAzureTargetsSpectraS3Request(ids []string) *ClearSuspectBlobAzureTargetsSpectraS3Request {
return &ClearSuspectBlobAzureTargetsSpectraS3Request{
content: buildIdListPayload(ids),
queryParams: queryParams,
}
}
func (clearSuspectBlobAzureTargetsSpectraS3Request *ClearSuspectBlobAzureTargetsSpectraS3Request) WithForce() …
```
> SA-192: Special cased requests with payload ids in Go module

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/ObjectNamesPayloadGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/ObjectNamesPayloadGenerator_Test.java
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
- ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java
**Changes**
- Special cased request handlers that take in a list of object names and convert them into the request payload `<Objects><Object Name="o1" /><Object Name="o2" />...</Objects>`
- Created new utils for properly detecting requests with this payload type
- Removed old method of generating these requests, which was erroneously special casing additional commands incorrectly.
- Created many new fixtures used in testing to ensure the classification utils are working as expected and not detecting false positives.
> Fix for SA-200 and SA-198 in Go module

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/helpers/PythonHelper.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeElement.java
- ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/client/client_class.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/create_client.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/requests/request.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/responses/response.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/static_classes.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/types/parser_function.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/types/static_type_descriptors.ftl
- ds3-autogen-python/src/main/resources/tmpls/python/commands/types/type_descriptor.ftl
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/BaseRequestGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/GetObjectRequestGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/ObjectsPayloadGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/PutObjectRequestGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/BaseResponseGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/GetObjectResponseGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/HeadResponseGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/PaginationResponseGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/type/BaseTypeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/helpers/PythonHelper_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/model/response/ResponsesToPythonCode_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/model/type/TypesToPythonCode_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/PythonDocGeneratorUtil_Test.java
- ds3-autogen-python3/src/main/resources/tmpls/python3/commands/p3_all_commands.ftl
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/request/P3PutObjectRequestGenerator_Test.java
**Changes**
- Updating the generated python code to have 4 spaces (was 2 spaces) per indent
- Updated generation of lists to remove unnecessary space before `:` to get rid of IDE warning
- ex: `'DataPolicyId' : None` -> `'DataPolicyId': None`
Generates the code in PRs:
https://github.com/SpectraLogic/ds3_python_sdk/pull/117
https://github.com/SpectraLogic/ds3_python3_sdk/pull/13
> PYTHONSDK-79: Updated python and python3 code to have 4 space per indent

- ds3-autogen-java/src/main/resources/tmpls/java/client/ds3client_impl_template.ftl
- ds3-autogen-java/src/main/resources/tmpls/java/client/ds3client_template.ftl
**Changes**
- Removed reference to the Java decorator `PutFolder` command in the java client template files
> JSDK-255: Removed put folder from java client templates

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/ClientGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/utils/Ds3RequestUtil.kt
- ds3-autogen-go/src/main/resources/tmpls/go/client/client_template.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/ClientGeneratorUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/Ds3RequestUtil_Test.java
**Changes**
- Updated client template
- Moved request path logic from requests to client module and updated accordingly
- Client now generates request builder for each command, and adds Http Verb and Path
- Updated existing tests
**Work To Do**
- Add the rest of the build options for each request
- optional parameters, required parameters, stream, metadata, checksum
```
func (client *Client) PutObject(request *models.PutObjectRequest) (*models.PutObjectResponse, error) {
}
networkRetryDecorator := …
```
> Updating go client to use new request builder design

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/ClientGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/BaseCommandGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/CommandGeneratorUtil.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/CommandModelGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/ClientGeneratorUtil_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/command/BaseCommandGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine_Test.java
**Changes**
Created a command generator which is used by the client generator. The command generator is used to generate the Go request builder code. The base command generator creates the lines for the http verb, path, required query parameters, and optional query parameters.
**TODO**
- Special case the command generator to add request payload streams, checksum, and headers when applicable.
```
package ds3
import (
"ds3/models"
)
func (client *Client) PutObject(request *models.PutObjectRequest) (*models.PutObjectResponse, error) {
WithOptionalQueryParam("job", request.Job). …
```
> GOSDK-8 continued: Created base command generator used within client

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/PutObjectCommandGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/PutObjectCommandGeneratorTest.kt
**Changes**
Put Object request builder now adds content reader, checksum, and metadata.
**Example Code Generation**
```
package ds3
import (
"ds3/models"
)
func (client *Client) PutObject(request *models.PutObjectRequest) (*models.PutObjectResponse, error) {
WithOptionalQueryParam("job", request.Job).
WithOptionalQueryParam("offset", networking.Int64PtrToStrPtr(request.Offset)).
WithReader(request.Content).
WithChecksum(request.Checksum).
WithHeaders(request.Metadata).
}
networkRetryDecorator := …
```
> GOSDK-8: Special cased Put Object client command generation in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/GetObjectCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/GetObjectCommandGeneratorTest.kt
**Changes**
Updated GetObject request builder to add checksum and headers/metadata. The metadata may contain the optional range header.
```
package ds3
import (
"ds3/models"
)
func (client *Client) GetObject(request *models.GetObjectRequest) (*models.GetObjectResponse, error) {
WithHttpVerb(HTTP_VERB_GET).
WithOptionalQueryParam("job", request.Job).
WithOptionalQueryParam("offset", networking.Int64PtrToStrPtr(request.Offset)).
WithChecksum(request.Checksum).
WithHeaders(request.Metadata).
}
networkRetryDecorator := …
```
> GOSDK-8: Special cased Get Object client command generation in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/ReaderPayloadCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/ReaderPayloadCommandGeneratorTest.kt
**Changes**
Added request payload to PutMultiPartUploadPart request builder.
```
package ds3
import (
"ds3/models"
)
func (client *Client) PutMultiPartUploadPart(request *models.PutMultiPartUploadPartRequest) (*models.PutMultiPartUploadPartResponse, error) {
WithQueryParam("part_number", strconv.Itoa(request.PartNumber)).
WithQueryParam("upload_id", request.UploadId).
WithReader(request.Content).
}
networkRetryDecorator := networking.NewNetworkRetryDecorator(&(client.sendNetwork), client.clientPolicy.maxRetries)
// Invoke …
```
> GOSDK-8: Special cased PutMultiPartUploadPart client command in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/Ds3PutObjectPayloadCommandGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/client/RequestBuildLine_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/Ds3PutObjectPayloadCommandGeneratorTest.kt
**Changes**
Added read closer to request builder for bulk put command.  The list of Ds3PutObjects is transformed into a stream within the client.
```
package ds3
import (
"ds3/models"
)
func (client *Client) PutBulkJobSpectraS3(request *models.PutBulkJobSpectraS3Request) (*models.PutBulkJobSpectraS3Response, error) {
WithPath("/_rest_/bucket/" + request.BucketName).
WithOptionalQueryParam("aggregating", networking.BoolPtrToStrPtr(request.Aggregating)).
WithOptionalVoidQueryParam("force", request.Force).
WithOptionalVoidQueryParam("ignore_naming_conflicts", request.IgnoreNamingConflicts).
WithOptionalQueryParam("implicit_job_id_resolution", …
```
> GOSDK-8: Special cased Bulk Put client command generation in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/Ds3GetObjectPayloadCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/Ds3GetObjectPayloadCommandGeneratorTest.kt
**Changes**
Added payload read closer to request builder for bulk get.
```
package ds3
import (
"ds3/models"
)
func (client *Client) GetBulkJobSpectraS3(request *models.GetBulkJobSpectraS3Request) (*models.GetBulkJobSpectraS3Response, error) {
WithPath("/_rest_/bucket/" + request.BucketName).
WithOptionalQueryParam("aggregating", networking.BoolPtrToStrPtr(request.Aggregating)).
WithOptionalQueryParam("chunk_client_processing_order_guarantee", networking.InterfaceToStrPtr(request.ChunkClientProcessingOrderGuarantee)).
WithOptionalQueryParam("implicit_job_id_resolution", networking.BoolPtrToStrPtr(request.ImplicitJobIdResolution)). …
```
> GOSDK-8: Special cased bulk get client command generation in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/ObjectNamePayloadCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/ObjectNamePayloadCommandGeneratorTest.kt
**Changes**
Added closable reader to client request builder for commands with request payloads of:
`<Objects><Object Name="o1" /><Object Name="o2" />...</Objects>`
Commands affected:
- GetPhysicalPlacementForObjectsSpectraS3Request
- GetPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request
- VerifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request
- VerifyPhysicalPlacementForObjectsSpectraS3Request
- EjectStorageDomainBlobsSpectraS3Request
**Sample Generated Code**
```
package ds3
import (
"ds3/models"
)
func (client *Client) VerifyPhysicalPlacementForObjectsSpectraS3(request *models.VerifyPhysicalPlacementForObjectsSpectraS3Request) (*models.VerifyPhysicalPlacementForObjectsSpectraS3Response, error) {
httpRequest, err := …
```
> GOSDK-8: Special cased client commands with object name list payloads in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/StringPayloadCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/StringPayloadCommandGeneratorTest.kt
**Changes**
Added read closer to request builder for commands with string request payloads.
```
package ds3
import (
"ds3/models"
)
func (client *Client) ReplicatePutJobSpectraS3(request *models.ReplicatePutJobSpectraS3Request) (*models.ReplicatePutJobSpectraS3Response, error) {
WithPath("/_rest_/bucket/" + request.BucketName).
WithQueryParam("replicate", "").
WithOptionalQueryParam("priority", networking.InterfaceToStrPtr(request.Priority)).
WithQueryParam("operation", "start_bulk_put").
WithReadCloser(buildStreamFromString(request.Content)).
}
networkRetryDecorator := …
```
> GOSDK-8: Special cased client commands with string payloads in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/PartsPayloadCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/PartsPayloadCommandGeneratorTest.kt
**Changes**
Added closable stream to commands with request payloads of part lists.
```
func (client *Client) CompleteMultiPartUpload(request *models.CompleteMultiPartUploadRequest) (*models.CompleteMultiPartUploadResponse, error) {
WithHttpVerb(HTTP_VERB_POST).
WithQueryParam("upload_id", request.UploadId).
WithReadCloser(buildPartsListStream(request.Parts)).
}
networkRetryDecorator := networking.NewNetworkRetryDecorator(&(client.sendNetwork), client.clientPolicy.maxRetries)
// Invoke the HTTP request.
response, requestErr := networkRetryDecorator.Invoke(httpRequest)
if …
```
> GOSDK-8: Special cased client commands with part list payloads in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/DeleteObjectsCommandGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-go/src/test/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/DeleteObjectsCommandGeneratorTest.kt
**Changes**
Added closable stream DeleteObjects request builder.
**Sample Code**
```
func (client *Client) DeleteObjects(request *models.DeleteObjectsRequest) (*models.DeleteObjectsResponse, error) {
WithHttpVerb(HTTP_VERB_POST).
WithPath("/" + request.BucketName).
WithQueryParam("delete", "").
WithOptionalVoidQueryParam("roll_back", request.RollBack).
WithReadCloser(buildDeleteObjectsPayload(request.ObjectNames)).
}
networkRetryDecorator := networking.NewNetworkRetryDecorator(&(client.sendNetwork), client.clientPolicy.maxRetries)
// Invoke the HTTP request.
response, requestErr := networkRetryDecorator.Invoke(httpRequest)
if requestErr != nil { …
```
> GOSDK-8: Special cased client commands with delete objects payload in Go module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/RequestGeneratorUtil_Test.java
- ds3-autogen-go/src/test/resources/input/putBucketSpectraS3.xml
**Changes**
- Deleting unused code
- in-lining code when utils are only called from one place
- fixed required constructor args to always take values not pointers
**Before**
```
func NewPutBucketSpectraS3Request(name *string) *PutBucketSpectraS3Request {
return &PutBucketSpectraS3Request{
Name: name,
}
}
```
**After**
```
func NewPutBucketSpectraS3Request(name string) *PutBucketSpectraS3Request {
return &PutBucketSpectraS3Request{
Name: name,
}
}
```
> GOSDK-8: Fixed incorrect generation of nullable constructor args in Go request handlers

- ds3-autogen-go/src/main/resources/tmpls/go/type/enum_unmarshal_to_string.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTypeTests.java
**Changes**
Added function `StringPtr` to all Go enums which converts an enum into a string pointer. If the enum is undefined, then a null is returned by the function. This is used to unmarshal optional enums.
```
package models
import (
"errors"
"fmt"
"bytes"
"log"
)
type SystemFailureType Enum
const (
SYSTEM_FAILURE_TYPE_RECONCILE_TAPE_ENVIRONMENT_FAILED SystemFailureType = 1 + iota
SYSTEM_FAILURE_TYPE_RECONCILE_POOL_ENVIRONMENT_FAILED SystemFailureType = 1 + iota
SYSTEM_FAILURE_TYPE_CRITICAL_DATA_VERIFICATION_ERROR_REQUIRES_USER_CONFIRMATION SystemFailureType = 1 + iota
SYSTEM_FAILURE_TYPE_MICROSOFT_AZURE_WRITES_REQUIRE_FEATURE_LICENSE SystemFailureType = 1 + iota
SYSTEM_FAILURE_TYPE_AWS_S3_WRITES_REQUIRE_FEATURE_LICENSE SystemFailureType = 1 + iota …
```
> GOSDK-8: Added StringPtr function to all Go enum generation

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/GetObjectResponseGenerator_Test.java
**Changes**
Updated generation of Get Object response to properly retrieve content on partial object gets.
Generated code was merged to the Go SDK in PR https://github.com/SpectraLogic/ds3_go_sdk/pull/47
> Fixed bug in Go response generation for Get Object on 206 response code

- ds3-autogen-go/README.md
- ds3-autogen-go/src/main/resources/tmpls/go/client/client_template.ftl
**Changes**
- adding new pathing to Go template imports to reflect removal `src` folder in Go SDK
Generated code was merged to Go SDK in PR https://github.com/SpectraLogic/ds3_go_sdk/pull/48
> SA-216: Updating template imports to reflect workspace change in Go SDK, and README

- ds3-autogen-go/src/main/resources/tmpls/go/request/get_object_request.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
Updates Go Get Object request to allow the setting of multiple ranges.
Generated code was merged into the Go SDK in PR: https://github.com/SpectraLogic/ds3_go_sdk/pull/49
> GOSDK-12: Updating Go Get Object to allow multiple ranges to be specified

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/typemodels/BaseTypeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/typemodels/ChecksumTypeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/typemodels/CommonPrefixGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/typemodels/TypeGeneratorUtil.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/Model.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/typemodels/BaseTypeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/typemodels/ChecksumTypeGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/typemodels/CommonPrefixGenerator_Test.java
**Changes**
- Updated imports in Java model generator from `ImmutableList` to `ImmutableSet`
- Removed imports of java objects representing primitives from model generation
This generates the code found in Java SDK PR: https://github.com/SpectraLogic/ds3_java_sdk/pull/530
> SA-218: Removing generation of superfluous imports in Java models

- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetFunctionalTests.java
- ds3-autogen-parser/src/main/java/com/spectralogic/ds3autogen/Ds3SpecNormalizer.java
- ds3-autogen-parser/src/main/java/com/spectralogic/ds3autogen/models/xml/typemap/TypeMap.java
- ds3-autogen-parser/src/main/java/com/spectralogic/ds3autogen/models/xml/typemap/TypeMapElement.java
- ds3-autogen-parser/src/main/kotlin/com/spectralogic/ds3autogen/converters/TypeConverter.kt
- ds3-autogen-parser/src/main/kotlin/com/spectralogic/ds3autogen/typemap/SdkTypeMapper.kt
- ds3-autogen-parser/src/main/resources/typeMap.json
- ds3-autogen-parser/src/test/kotlin/com/spectralogic/ds3autogen/converters/TypeConverterTest.kt
- ds3-autogen-parser/src/test/kotlin/com/spectralogic/ds3autogen/typemap/SdkTypeMapperTest.kt
- ds3-autogen-parser/src/test/resources/testTypeMap.json
**Changes**
Added type converting to parsing module in autogen so that specified types can be modified across all SDKs consistently. Types to be changed are specified within a json file.  Created default type mapping file which contains TapeType -> String
> SA-217: Adding type converter to parser module

- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoModelFixturesUtil.java
Found minor bug in generation of Go parsing code for change related to TapeType -> String.  This exposed an issue when parsing a response payload that contain a list of tags (content of type string) that are not encapsulated in a tag.  This fixes the parsing code to properly handle this scenario.
Generated code: https://github.com/SpectraLogic/ds3_go_sdk/pull/50
> SA-217: Fixed minor bug in generation of Go parsing code

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/response/BaseResponseGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/response/StringParsePayload.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/BaseResponseGenerator_Test.java
Generated code already merged:
https://github.com/SpectraLogic/ds3_python_sdk/pull/119
https://github.com/SpectraLogic/ds3_python3_sdk/pull/15
> PYTHONSDK-80: Fixed python response handlers with string response payloads

- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/java/responseparser/head_object_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
**Changes**
Generates the Head Object response handler and response parser to include the blob checksum header parsing.
Generates the code in Java SDK PR: https://github.com/SpectraLogic/ds3_java_sdk/pull/541
**Generated Response Handler Code**
```
package com.spectralogic.ds3client.commands;
import com.spectralogic.ds3client.commands.interfaces.AbstractResponse;
import com.spectralogic.ds3client.networking.Metadata;
import com.spectralogic.ds3client.models.ChecksumType;
import com.google.common.collect.ImmutableMap;
public class HeadObjectResponse extends AbstractResponse {
public enum Status { EXISTS, DOESNTEXIST, UNKNOWN }
private final ImmutableMap<Long, String> blobChecksums;
private final ChecksumType.Type blobChecksumType;
private final Metadata metadata;
private final long …
```
> Updating head object response generation in java for 4.1 API

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/response/HeadObjectResponseGenerator.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/HeadObjectResponseGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/HeadResponseGenerator_Test.java
Generates 4.1 blob checksum header support in Head Object for Python and Python3 modules.
- Created `HeadObjectResponseGenerator` to special case the header parsing code
- Updated existing tests
> SA-229: 4.1 API support for python and python3

- ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
Generates code for merged C SDK PR: https://github.com/SpectraLogic/ds3_c_sdk/pull/220
> CSDK-171: Removing JobChunkClientProcessingOrderGuarantee from C request payload body

- contracts/5_0_x_contract.xml
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/requestmodels/GetObjectRequestGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/java/models/bulk_object_template.ftl
- ds3-autogen-java/src/main/resources/tmpls/java/models/s3object_model_template.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/resources/input/ejectStorageDomainBlobs.xml
- ds3-autogen-java/src/test/resources/input/getObjectRequestHandler.xml
- ds3-autogen-java/src/test/resources/input/stageObjectsJob.xml
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Helper.java
**Changes**
- Updating 5.0 contract
- Special casing new command Stage Objects Job Request same as Get Bulk Job Request.
- Fixing Get Object request generation where new VersionId was being added as a constructor parameter rather than just an optional parameter.
- Updated request classification functions to match 5.0 changes
**Note**
Changes to the request classification utils breaks tests in modules that are still on 4.1.x API target
> 5.0 API generation for Java module

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/IdListRequestPayloadGenerator.java
- ds3-autogen-python/src/main/kotlin/com/spectralogic/ds3autogen/python/PythonCodeGeneratorInterface.kt
- ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/IdListRequestPayloadGenerator_Test.java
- ds3-autogen-python/src/test/resources/input/requests/clearSuspectBlobAzureTargets.xml
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/Python3CodeGenerator.kt
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/generators/request/P3IdListRequestGenerator.kt
- ds3-autogen-python3/src/main/resources/tmpls/python3/commands/p3_all_commands.ftl
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/Python3FunctionalTests.java
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/request/P3IdListRequestGenerator_Test.java
- ds3-autogen-python3/src/test/resources/input/requests/clearSuspectBlobAzureTargets.xml
- ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
- ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
- ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java
**Changes**
- Updated request classification util to include `ClearSuspectBlobDs3TargetsRequest` as having a request payload of ids
- Added `IdsList` class to python modules for use in marshaling the new request payload. _Note: there is a separate implementation in Python and Python 3 given that `basestring` was renamed to `str` in Python 3._
- Special cased commands with id lists as request payloads to properly handle request payloads.
Generates Python SDK code found in PR: https://github.com/SpectraLogic/ds3_python_sdk/pull/126
Generates Python 3 SDK code found in PR: https://github.com/SpectraLogic/ds3_python3_sdk/pull/20
> SA-195 & SA-196: Special cased commands with request payload of id list in python modules

- ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/NetCodeGenerator.java
- ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/generators/requestmodels/PartialObjectRequestPayloadGenerator.java
- ds3-autogen-net/src/main/resources/tmpls/net/request/bulk_get_request.ftl
- ds3-autogen-net/src/main/resources/tmpls/net/request/eject_storage_domain_blobs_request.ftl
- ds3-autogen-net/src/main/resources/tmpls/net/request/partial_objects_request_payload.ftl
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetCodeGenerator_Test.java
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetFunctionalTests.java
- ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/generators/requestmodels/PartialObjectRequestPayloadGenerator_Test.java
Fixed the generation of requests that can have request payloads describing partial objects in .Net module.
Generates the code merged in Net SDK PR: https://github.com/SpectraLogic/ds3_net_sdk/pull/298
> NETSDK-147: Fixing request generation with partial object payloads in .Net module

- ds3-autogen-go/src/main/resources/tmpls/go/request/put_object_request.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
Removing generation of constant `AMZ_META_HEADER` from within PutObjectRequest to reflect previous refactor.
> SA-238: Removed constant from PutObjectRequest template in Go module

- ds3-autogen-c/src/main/resources/templates/source-templates/ds3_requests.ftl
- ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
- ds3-autogen-c/src/main/resources/templates/source-templates/xml_helpers.ftl
In the C generated SDK, this enables the request payload marshaling functions to be unit tested. The resulting code was merged into the C SDK master branch in commit https://github.com/SpectraLogic/ds3_c_sdk/commit/8bc3d38c43d80d0910dd04d592a880cf85ef6e4b
> exporting xml marshaling functions in c templates

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/BaseClientGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/ClientModelGeneratorUtils.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/GetObjectCommandGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/response/GetObjectResponseGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/client/BaseClient.java
- ds3-autogen-python/src/main/kotlin/com/spectralogic/ds3autogen/python/PythonCodeGeneratorInterface.kt
- ds3-autogen-python/src/main/resources/tmpls/python/commands/client/client_class.ftl
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/client/GetObjectCommandGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/GetObjectResponseGenerator_Test.java
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/Python3CodeGenerator.kt
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/generators/response/P3GetObjectResponseGenerator.kt
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/response/P3GetObjectResponseGenerator_Test.java
- Had to special case response handler and client command for get object in order to allow buffer size to be setable.
- Had to special case response handler separately for 2.7 and 3.6 version due to syntax differences when referencing super constructor.
> Updating python generation to support settable buffer size in get object

- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/BaseClientGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/ClientModelGeneratorUtils.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/GetObjectCommandGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/response/GetObjectResponseGenerator.java
- ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/client/BaseClient.java
- ds3-autogen-python/src/main/kotlin/com/spectralogic/ds3autogen/python/PythonCodeGeneratorInterface.kt
- ds3-autogen-python/src/main/resources/tmpls/python/commands/client/client_class.ftl
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/client/BaseClientGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/client/GetObjectCommandGenerator_Test.java
- ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/GetObjectResponseGenerator_Test.java
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/Python3CodeGenerator.kt
- ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/generators/response/P3GetObjectResponseGenerator.kt
- ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/response/P3GetObjectResponseGenerator_Test.java
Cherry-picked commits from master (4.0 target) from PR https://github.com/SpectraLogic/ds3_autogen/pull/484
Verified python 5.0 code is generated correctly
> 5.0 branch: Updating python generation to support settable buffer size in get object

- .travis.yml
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
- ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
- ds3-autogen-go/src/main/resources/tmpls/go/type/checksum_type_enum.ftl
- ds3-autogen-go/src/main/resources/tmpls/go/type/enum_type.ftl
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
- ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls_Test.java
Adding instantiation step to nullable enums before attempting to set value.
> GOSDK-25: Unmarshaling optional enums in response payloads causes panic

- contracts/5_1_0_1664144_contract.xml
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
- ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
- ds3-autogen-java/src/main/resources/tmpls/java/copyright.ftl
- ds3-autogen-java/src/main/resources/tmpls/java/responseparser/head_object_parser.ftl
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
- ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
- Added 5.1.x contract
- Updated copyright generation date for Java SDK.
- JSDK-297: Add new Header value to HEAD Object. Added special header parsing for head object call.
Code generated by this version can be seen: https://github.com/SpectraLogic/ds3_java_sdk/pull/577
> JSDK-297: updating generation for Java SDK for BP 5.1.2 API.

- ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
- ds3-autogen-go/src/main/resources/tmpls/go/response/response_get_object_template.ftl
Updating Go SDK to close file handles always within response handlers instead of in the response parsing to handle error scenarios and no response payload scenarios.
Generated code in https://github.com/SpectraLogic/ds3_go_sdk/pull/94
> GOSDK-29: SDK leaks memory from unclosed HTTP response bodies

- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/ParameterConverter.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/ParameterHelper.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/RequestHelper.java
- ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/StructMember.java
- ds3-autogen-c/src/main/resources/templates/source-templates/modify_request.ftl
Fixed generation of C boolean query parameters to allow for setting of true/false values. Also special cased the naming of the protected flag to avoid key word conflict.
> C SDK: Enabling aggregating on a job sets value to null instead of true
