ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/converters/RequestConverter.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/NotificationType.java
ds3-autogen-java/src/main/resources/tmpls/create_notification_request_template.tmpl
ds3-autogen-java/src/main/resources/tmpls/delete_notification_request_template.tmpl
ds3-autogen-java/src/main/resources/tmpls/get_notification_request_template.tmpl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
ds3-autogen-java/src/test/resources/input/createJobCompletedNotificationRegistrationRequestHandler.xml
ds3-autogen-java/src/test/resources/input/deleteJobCreatedNotificationRegistrationRequestHandler.xml
ds3-autogen-java/src/test/resources/input/getJobCompletedNotificationRegistrationsRequestHandler.xml

Test Coverage:
97% class coverage, 94% line coverage in ds3-autogen-java

Implemented special casing for notification request handlers in java module

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/CCodeGenerator.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/TypeConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/CHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Type.java
ds3-autogen-c/src/main/resources/templates/CopyrightHeader.tmplt
ds3-autogen-c/src/main/resources/templates/Ds3RequestHandler.tmplt
ds3-autogen-c/src/main/resources/templates/TypeEnumConstant.tmplt
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java

For JIRA Task SA-19: http://jira.eng.sldomain.com/browse/SA-19?filter=-1
Testing started at 2:29 PM ...
2:29:45 PM: Executing external tasks 'cleanTest test'...
:ds3-autogen-c:cleanTest
:ds3-autogen-api:compileJava UP-TO-DATE
:ds3-autogen-api:processResources UP-TO-DATE
:ds3-autogen-api:classes UP-TO-DATE
:ds3-autogen-api:jar UP-TO-DATE
:ds3-autogen-utils:compileJava UP-TO-DATE
:ds3-autogen-utils:processResources UP-TO-DATE
:ds3-autogen-utils:classes UP-TO-DATE
:ds3-autogen-utils:jar UP-TO-DATE
:ds3-autogen:compileJava UP-TO-DATE
:ds3-autogen:processResources UP-TO-DATE
:ds3-autogen:classes UP-TO-DATE
:ds3-autogen:jar UP-TO-DATE
:ds3-autogen-c:compileJava UP-TO-DATE
:ds3-autogen-c:processResources
:ds3-autogen-c:classes
:ds3-autogen-c:compileTestJava
:ds3-autogen-c:processTestResources …

Enum constants

---

ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/NetCodeGenerator.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/NetHelper.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/generators/requestmodels/GetObjectRequestGenerator.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/utils/GeneratorUtils.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/generators/requestmodels/BaseRequestGenerator_Test.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/generators/requestmodels/BulkPutRequestGenerator_Test.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/generators/requestmodels/GetObjectRequestGenerator_Test.java

Net package code coverage: 77% classes, 92% line coverage

Added javadoc and tests for net package

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/CCodeGenerator.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/SourceConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/EnumHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/StructHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/FreeableType.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Header.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Request.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Source.java
ds3-autogen-c/src/main/resources/templates/header-templates/RequestPrototype.ftl
ds3-autogen-c/src/main/resources/templates/header-templates/TypedefStruct.ftl
ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorAmazonS3InitRequests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorAmazonS3Requests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3InitRequests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3Requests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/SourceConverter_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/StructHelper_Test.java
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/collections/GuavaCollectors.java

Implement SourceConverter to move all logic out of the Source model constructor.  Pull in a few related functions from StructHelper.
Move ordering / filtering from CCodeGenerator into SourceConverter.
Update all tests for tweaked Source creation.  Also make some tests more targeted in testing output rather than end-to-end ApiContract parsing through code gen.
Add a RequestPrototype template, and process in ds3_h.ftl
Remove useless .keep files

Add a collections package for using with streams / lambdas.

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/CCodeGenerator.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/ParameterConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/RequestConverter.java
ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_request_h.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/EnumToString.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/source_post_response_matchers.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/source_pre_init_functions.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3InitRequests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetCodeGenerator_ModelParsers_Test.java
ds3-autogen-parser/src/main/resources/typeNameMap.json

add generation of static files to CCodeGenerator
tweaks for new functions and types in templates
change SdkName for BucketApiBean from Ds3Bucket to BucketDetails
change SdkName for NodeApiBean from Ds3Node to Endpoint
update all tests to reflect the previous 2 changes

special case responseType java.lang.String to be a ds3_str

---

ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/generators/requestmodels/BaseRequestGenerator.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/generators/requestmodels/GetObjectRequestGenerator.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/utils/GeneratorUtils.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/utils/GeneratorUtils_Test.java
ds3-autogen-python/build.gradle
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/BaseRequestGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/RequestModelGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/RequestModelGeneratorUtils.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/helpers/PythonHelper.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/commands/CommandSet.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/BaseRequest.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/utils/GeneratorUtils.java
ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
ds3-autogen-python/src/main/resources/tmpls/python/commands/requests/request.ftl
ds3-autogen-python/src/main/resources/tmpls/python/common/copyright.ftl
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/BaseRequestGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/helpers/PythonHelper_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/FunctionalTestHelper.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/GeneratorUtils_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/TestPythonGeneratedCode.java
ds3-autogen-python/src/test/resources/input/.gitattributes
ds3-autogen-python/src/test/resources/input/requests/deleteJobCreatedNotificationRegistrationRequest.xml
ds3-autogen-python/src/test/resources/input/requests/simpleRequest.xml
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/RequestConverterUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/RequestConverterUtil_Test.java

Python module code coverage: 100% classes, 94% lines

Python request handler generation

---

ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/utils/NetNullableVariableUtils.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/utils/NetNullableVariableUtils_Test.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/type/BaseTypeGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/type/TypeModelGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/helpers/PythonHelper.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/commands/CommandSet.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeAttribute.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeContent.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeDescriptor.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeElement.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/type/TypeElementList.java
ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
ds3-autogen-python/src/main/resources/tmpls/python/commands/types/parser_function.ftl
ds3-autogen-python/src/main/resources/tmpls/python/commands/types/type_descriptor.ftl
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/type/BaseTypeGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/helpers/PythonHelper_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/model/type/TypesToPythonCode_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/FunctionalTestHelper.java
ds3-autogen-python/src/test/resources/input/types/simpleType.xml
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3TypeClassificationUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3TypeClassificationUtil_Test.java

Python module code coverage: 100% classes, 97% lines

Python model descriptor generation and python xml parser

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/RequestConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/ParameterHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/RequestHelper.java
ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/request-templates/InitRequest.ftl
ds3-autogen-c/src/main/resources/templates/request-templates/RequestWithRequestAndResponsePayload.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/source_post_response_matchers.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3InitRequests_Test.java

make request payload paremeters un-const
properly assign request payload to request object
tweak helper functions _ds3_bulk_object_from_file,ds3_convert_file_list_with_basepath,  ds3_convert_object_list,

add trailing slash to SpectraS3 resource path

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/StructConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/StructHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/StructMemberHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Struct.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/StructMember.java
ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/source_post_response_matchers.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/StructHelper_Test.java

This pull request includes changes from pull request https://github.com/SpectraLogic/ds3_autogen/pull/228 that was opened 6 days ago, plus fixes issues related to parsing of elements with and without encapsulating element tags.

Encapsulating element tag parsing

---

ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/BaseRequestGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/RequestModelGeneratorUtils.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/BaseRequest.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/queryparam/BaseQueryParam.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/queryparam/OperationQueryParam.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/queryparam/QueryParam.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/request/queryparam/VoidQueryParam.java
ds3-autogen-python/src/main/resources/tmpls/python/commands/requests/request.ftl
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/BaseRequestGenerator_Test.java

Code Coverage in Python Module: 100% classes, 98% lines
Python SDK tests passing: 28/43

Requests add required params to query param list in python requests

---

ds3-autogen-c/src/main/resources/templates/header-templates/RequestCommentDocumentation.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl

Also make _init_request_payload() static

Fix formatting of ds3.h function prototype comments for doxygen.

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/StructConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/StructHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/StructMemberHelper.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/StructConverter_Test.java

<CommonPrefixes><Prefix>movies/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>scores/</Prefix></CommonPrefixes>
Each CommonPrefixes block needs to be parsed separately

Fix parser generation with CommonPrefix elements

---

contracts/3_2_2_contract.xml

Manually updated 1 response type from TreeSet to DataPolicy array in contract

Updated 3.2.2 contract

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
ds3-autogen-java/src/main/resources/tmpls/copyright.ftl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java
ds3-autogen-java/src/test/resources/input/deleteBucket.xml
ds3-autogen-java/src/test/resources/input/deleteObject.xml

Tests added based on example code available in initial implementation of network refactor :
https://github.com/rpmoore/ds3_java_sdk/tree/net_client_update/ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers

Improved functional testing of base response parser generation

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/EnumConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/EnumHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Enum.java
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/EnumHelper_Test.java

Eliminate some build warnings in the C SDK

Do not generate enum matchers where not needed

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/converters/ClientConverter.java
ds3-autogen-java/src/main/resources/tmpls/client/ds3client_impl_template.ftl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/converters/ClientConverter_Test.java

**Changes**
- Updated Ds3ClientImpl to use response parsers
- Updated special cased client generation of GetObject to use there response parser with channel
- Added handleExceptions method to Ds3ClientImpl template
Code cleanup
--
Generated Code: Ds3ClientImpl.java with GetBucket and GetObject
--
```
/*
*
*
*   This file is distributed on an "AS IS" …
```

Updated Ds3ClientImpl generation in java module

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/ResponseGeneratorUtil.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/ResponseParserGeneratorUtil.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/ResponseParser.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/BaseParseResponse.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/EmptyParseResponse.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/NullParseResponse.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/parseresponse/StringParseResponse.java
ds3-autogen-java/src/main/resources/tmpls/responseparser/response_parser_template.ftl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/BaseResponseGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/AllocateJobChunkParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/BaseResponseParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetJobChunksReadyParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/GetObjectParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadBucketParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/parseresponse/ParseResponse_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/utils/TestHelper.java

**Changes**
- Added parsing of pagination headers to response parsers (when applicable)
- Added pagination header vars to response handlers (when applicable)
--
Example Generated Code: Get Users Response Parser
--
```
/*
*
*
*   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
*   CONDITIONS OF ANY KIND, either express or implied. See the License for …
```

Added pagination header parsing

---

ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/CCodeGenerator.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/ParameterConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/RequestConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/RequestHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Parameter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/models/Request.java
ds3-autogen-c/src/main/resources/templates/header-templates/RequestCommentDocumentation.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_net_c.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorAmazonS3InitRequests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorAmazonS3Requests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3InitRequests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3Requests_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGenerator_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/HeaderConverter_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/RequestConverter_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/SourceConverter_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/StructHelper_Test.java
ds3-autogen-c/src/test/resources/input/testCommandDocumentation.json
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/ConverterUtil.java
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Helper.java

Also fix template for ds3_net.c::escape_url_object_name() to encode the + sign (already fixed in C SDK)

C SDK Documentation and tests for Requests and Parameters

---

ds3-autogen-c/src/main/resources/templates/other-templates/ds3_net_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/metadata.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/modify_request.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/xml_helpers.ftl

also patch various bug fixes that were applied directly to the C SDK

Updates for C SDK with cmake

---

ds3-autogen-java/src/main/resources/tmpls/client/ds3client_impl_template.ftl
ds3-autogen-java/src/main/resources/tmpls/client/ds3client_template.ftl

**Changes**
Added the new overload function to the client and clientImpl templates

Added overload of get object command for custom parsing

---

contracts/3_4_0_contract.xml

**Note**
Changes do not effect code generation

Updating 3.4.0 contract to BP RC1 version

---

README.md
ds3-autogen-c/README.md
ds3-autogen-java/README.md
ds3-autogen-net/README.md
ds3-autogen-python/README.md

README's include instructions on how to generate and integrate code into each SDK.

SA-169: Created README for language modules

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java

**Changes**
- Added test to verify correct request generator for special casing
- Fixed special casing for `EjectStorageDomainBlobsRequest`
- Added more request fixtures for use in testing

Added test and fixed bug for requests with Ds3ObjectList request payload in Go module

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/MultipartUploadPayloadGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/MultipartUploadPayloadGenerator_Test.java
ds3-autogen-go/src/test/resources/input/completeMultipartUpload.xml

**Changes**
- Created generator for request handler with CompleteMultipartUpload request payload

SA 177- Special cased Go's CompleteMultipartUpload request handler generation

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/DeleteObjectsRequestGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/DeleteObjectsRequestGenerator_Test.java
ds3-autogen-go/src/test/resources/input/deleteObjects.xml

**Changes**
- Created request generator for DeleteObjects command which has a request payload of object names to be deleted

Special cased delete objects request generation in Go module

---

ds3-autogen-go/src/main/resources/tmpls/go/client/client_template.ftl

Added missing import to Go template

Added networking import to Go client template

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/PutObjectRequestGenerator.kt
ds3-autogen-go/src/main/resources/tmpls/go/request/put_object_request.ftl
ds3-autogen-go/src/main/resources/tmpls/go/request/with_headers.ftl
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/PutObjectRequestGenerator_Test.java
ds3-autogen-go/src/test/resources/input/putObject.xml

Generated code:
```
package models
import (
"net/url"
"net/http"
"strings"
"strconv"
)
const ( AMZ_META_HEADER = "x-amz-meta-" )
type PutObjectRequest struct {
objectName string
checksum networking.Checksum
headers *http.Header
job string
offset int64
}
func NewPutObjectRequest(bucketName string, objectName string, content networking.ReaderWithSizeDecorator) *PutObjectRequest {
return &PutObjectRequest{
bucketName: bucketName,
objectName: objectName,
content: content,
checksum: networking.NewNoneChecksum(),
headers: &http.Header{},
queryParams: queryParams,
}
}
func (putObjectRequest *PutObjectRequest) WithJob(job string) *PutObjectRequest { …
```

Special cased Go's PutObject request handler

---

ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_connection_c.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_connection_h.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_net_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/client.ftl

to match after https://github.com/SpectraLogic/ds3_c_sdk/pull/197

Update templates 

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/models/withconstructor/MaxUploadSizeWithConstructor.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/requestmodels/BulkRequestGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/models/withconstructor/WithConstructor_Test.java

Generates the code found in Java SDK PR https://github.com/SpectraLogic/ds3_java_sdk/pull/478

Fixed bug in java generation of bulk put

---

README.md
ds3-autogen-go/README.md

Module README outlines how to generate and integrate Go code into Go SDK.

SA-188: Added Go module README

---

ds3-autogen-net/README.md
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/NetCodeGenerator.java
ds3-autogen-net/src/main/resources/tmpls/net/request/ids_request_payload.ftl
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetCodeGenerator_Test.java
ds3-autogen-net/src/test/resources/input/clearSuspectBlobAzureTargetsRequest.xml

Generates code which can be found in PR https://github.com/SpectraLogic/ds3_net_sdk/pull/276

SA-194: Special cased requests with ids payload in net module

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/Ds3PutObjectPayloadGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/Ds3PutObjectPayloadGenerator_Test.java
ds3-autogen-go/src/test/resources/input/putBulkJob.xml
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
ds3-autogen-python/src/test/resources/input/requests/putBulkJob.xml
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java

**Changes**
- Updated Go's PutBulkJobSpectraS3Request to have request payload `objects []Ds3PutObject`
- Updated util for detecting put bulk job request to be more complete
- Fixed poorly defined test in Python module to verify update to util did not change expected behavior
```
package models
import (
"net/url"
"net/http"
"strconv"
)
type PutBulkJobSpectraS3Request struct {
aggregating bool
implicitJobIdResolution bool
maxUploadSize int64
minimizeSpanningAcrossMedia bool
name *string
priority Priority
verifyAfterWrite bool
}
func NewPutBulkJobSpectraS3Request(bucketName string, objects []Ds3PutObject) *PutBulkJobSpectraS3Request { …
```

SA-201: Updated Go generation of put bulk job request handler

---

build.gradle
ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/BaseRequestGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/Ds3PutObjectPayloadGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/GetBulkJobRequestGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/GetObjectRequestGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/PutObjectRequestGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequestPayloadGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/RequiredObjectsPayloadGenerator.kt
ds3-autogen-go/src/main/resources/tmpls/go/request/get_bulk_job_request.ftl
ds3-autogen-go/src/main/resources/tmpls/go/request/request_body.ftl
ds3-autogen-go/src/main/resources/tmpls/go/request/request_struct.ftl
ds3-autogen-go/src/main/resources/tmpls/go/request/with_constructors_verb_path.ftl
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/GetBulkJobRequestGenerator_Test.java
ds3-autogen-go/src/test/resources/input/getBulkJob.xml
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/GetObjectResponseGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/RetryAfterResponseGenerator.java
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java

**Changes**
- Updated GetBulkJob to have two constructors, with request payloads `objectNames []string` and `[]Ds3GetObject`
- Made util for detecting GetBulkJob request more robust
- Refactored Go request handler templates for maximal code re-usage
```
package models
import (
"net/url"
"net/http"
"strconv"
)
type GetBulkJobSpectraS3Request struct {
aggregating bool
chunkClientProcessingOrderGuarantee JobChunkClientProcessingOrderGuarantee
implicitJobIdResolution bool
name *string
priority Priority
}
func NewGetBulkJobSpectraS3Request(bucketName string, objectNames []string) *GetBulkJobSpectraS3Request {
queryParams.Set("operation", …
```

SA-199: Updated Go GetBulkJob request handler to have multiple constructors

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/Ds3VerifyObjectPayloadGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/request/Ds3VerifyObjectPayloadGenerator_Test.java
ds3-autogen-go/src/test/resources/input/verifyBulkJob.xml
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java

**Changes**
- Updated Go generation of `VerifyBulkJobSpectraS3Request` to have request payload of `objects []Ds3VerifyObject`
```
package models
import (
"net/url"
"net/http"
"strconv"
)
type VerifyBulkJobSpectraS3Request struct {
aggregating bool
name *string
priority Priority
}
func NewVerifyBulkJobSpectraS3Request(bucketName string, objects []Ds3VerifyObject) *VerifyBulkJobSpectraS3Request {
queryParams.Set("operation", "start_bulk_verify")
return &VerifyBulkJobSpectraS3Request{
bucketName: bucketName,
content: buildDs3VerifyObjectListStream(objects),
queryParams: queryParams,
}
}
func (verifyBulkJobSpectraS3Request …
```

SA-203: Updated Go VerifyBulkJob request handler

---

ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/parser/BaseTypeParserGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/models/parser/ParseChildNodeImpls_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/utils/GoModelFixturesUtil.java

Generated code can be found in PR https://github.com/SpectraLogic/ds3_go_sdk/pull/35

SA-202: Fixed generation of Go parser assignment to Ds3Type pointers

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaCodeGenerator_Test.java
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java

Generated code can be found in PR: https://github.com/SpectraLogic/ds3_java_sdk/pull/494

SA-204: Fixed erroneous special casing of some Java request handlers

---

ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/NetCodeGenerator.java
ds3-autogen-net/src/main/java/com/spectralogic/ds3autogen/net/generators/requestmodels/PartsRequestPayloadGenerator.java
ds3-autogen-net/src/main/resources/tmpls/net/request/parts_request_payload.ftl
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetCodeGenerator_Test.java
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/generators/requestmodels/PartsRequestPayloadGenerator_Test.java
ds3-autogen-net/src/test/resources/input/completeMultiPartUploadRequest.xml

**Changes**
In Net module
- Special cased CompleteMultiPartUpload request handler
- Added unit tests
Generated code can be found in PR https://github.com/SpectraLogic/ds3_net_sdk/pull/278

SA-206: Special cased Net request handler for CompleteMultiPartUpload

---

ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/client/BaseClientGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/model/client/BaseClient.java
ds3-autogen-python/src/main/resources/tmpls/python/commands/client/client_class.ftl
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/utils/FunctionalTestHelper.java

Updates the generation of python and python3 to add type checking to request handlers passed in to client commands.

PYTHONSDK-82: updating python generation of client to type check request handlers

---

ds3-autogen-net/src/main/resources/tmpls/net/parsers/response/head_object_parser.ftl
ds3-autogen-net/src/main/resources/tmpls/net/response/head_object_response.ftl
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetFunctionalTests.java

Generates Net SDK code merged in: https://github.com/SpectraLogic/ds3_net_sdk/pull/295

SA-227 4.1 API for Net module with blob checksum header support

---

ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/HeadObjectResponseGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/HeadObjectResponseGenerator_Test.java
ds3-autogen-go/src/test/resources/input/headObjectRequest.xml

Generates the Head Object response code found in PR: https://github.com/SpectraLogic/ds3_go_sdk/pull/53

SA-230: Adding 4.1 blob checksum parsing to Go module

---

ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/request-templates/HeadObjectRequest.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_requests.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/free_custom_types.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3Requests_Test.java
ds3-autogen-c/src/test/resources/input/HeadObjectRequest.xml

Adding blob checksum header parsing to Head Object in C module.
Generates code found in C SDK PR: https://github.com/SpectraLogic/ds3_c_sdk/pull/218

SA-228: 4.1 generation for C module

---

ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/request-templates/HeadObjectRequest.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_c.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/ds3_requests.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/free_custom_types.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/CCodeGeneratorSpectraS3Requests_Test.java
ds3-autogen-c/src/test/resources/input/HeadObjectRequest.xml
ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/response/HeadObjectResponseGenerator.kt
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoCodeGenerator_Test.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/GoFunctionalTests.java
ds3-autogen-go/src/test/java/com/spectralogic/ds3autogen/go/generators/response/HeadObjectResponseGenerator_Test.java
ds3-autogen-go/src/test/resources/input/headObjectRequest.xml
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator.java
ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator.java
ds3-autogen-java/src/main/resources/tmpls/java/responseparser/head_object_parser.ftl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responsemodels/HeadObjectResponseGenerator_Test.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/responseparser/HeadObjectParserGenerator_Test.java
ds3-autogen-net/src/main/resources/tmpls/net/parsers/response/head_object_parser.ftl
ds3-autogen-net/src/main/resources/tmpls/net/response/head_object_response.ftl
ds3-autogen-net/src/test/java/com/spectralogic/ds3autogen/net/NetFunctionalTests.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/response/HeadObjectResponseGenerator.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/HeadObjectResponseGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/response/HeadResponseGenerator_Test.java

Contains all the commits for generating 4.1 API across all language modules. All commits have passed code review in separate PRs.

Updating main branch from 4.0 to 4.1 API generation

---

ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/PythonCodeGenerator.java
ds3-autogen-python/src/main/java/com/spectralogic/ds3autogen/python/generators/request/IdListRequestPayloadGenerator.java
ds3-autogen-python/src/main/kotlin/com/spectralogic/ds3autogen/python/PythonCodeGeneratorInterface.kt
ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonCodeGenerator_Test.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/PythonFunctionalTests.java
ds3-autogen-python/src/test/java/com.spectralogic.ds3autogen.python/generators/request/IdListRequestPayloadGenerator_Test.java
ds3-autogen-python/src/test/resources/input/requests/clearSuspectBlobAzureTargets.xml
ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/Python3CodeGenerator.kt
ds3-autogen-python3/src/main/kotlin/com/spectralogic/ds3autogen/python3/generators/request/P3IdListRequestGenerator.kt
ds3-autogen-python3/src/main/resources/tmpls/python3/commands/p3_all_commands.ftl
ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/Python3FunctionalTests.java
ds3-autogen-python3/src/test/java/com/spectralogic/ds3autogen/python3/generators/request/P3IdListRequestGenerator_Test.java
ds3-autogen-python3/src/test/resources/input/requests/clearSuspectBlobAzureTargets.xml
ds3-autogen-test-util/src/main/java/com/spectralogic/ds3autogen/testutil/Ds3ModelFixtures.java
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java
ds3-autogen-utils/src/test/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil_Test.java

Same commit that was merged to master in PR: https://github.com/SpectraLogic/ds3_autogen/pull/469
Merging to 5.0 branch in preparation to updating python to 5.0 API

Adding special cased commands with request payload of id list in python and python 3

---

ds3-autogen-net/src/main/resources/tmpls/net/parsers/typeset/primitive_parsers.ftl

Generates code for Net SDK PR: https://github.com/SpectraLogic/ds3_net_sdk/pull/303

fixing common prefixes bug in net sdk

---

contracts/5_0_x_contract.xml
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/converters/RequestConverter.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/ParameterHelper.java
ds3-autogen-c/src/main/java/com/spectralogic/ds3autogen/c/helpers/RequestHelper.java
ds3-autogen-c/src/main/resources/templates/header-templates/ds3_h.ftl
ds3-autogen-c/src/main/resources/templates/other-templates/ds3_request_h.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/free_custom_types.ftl
ds3-autogen-c/src/main/resources/templates/source-templates/internal_request_processors.ftl
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/Parameter_Test.java
ds3-autogen-c/src/test/java/com/spectralogic/ds3autogen/c/RequestConverter_Test.java

**Changes**
- Updated 5.0 contract
- Special cased suspect blob commands to have request payload of ids in c module

Added ids request payload generation in c module

---

contracts/5_1_x_1710735_contract.xml
ds3-autogen-go/src/main/java/com/spectralogic/ds3autogen/go/GoCodeGenerator.java
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/BaseClientGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/client/command/GetObjectCommandGenerator.kt
ds3-autogen-go/src/main/kotlin/com/spectralogic/ds3autogen/go/generators/request/CompleteBlobRequestGenerator.kt
ds3-autogen-go/src/main/resources/tmpls/go/request/with_headers.ftl
ds3-autogen-utils/src/main/java/com/spectralogic/ds3autogen/utils/Ds3RequestClassificationUtil.java

Used to generate Go SDK PR: https://github.com/SpectraLogic/ds3_go_sdk/pull/96

OTHER: Updating Go SDK generation to include optional checksum and metadata parameters on CompleteBlob request

---

ds3-autogen-c/src/main/resources/templates/other-templates/ds3_net_c.ftl

Autogen code for C SDK issue: https://github.com/SpectraLogic/ds3_c_sdk/pull/230

Fix for C SDK Issue-229

---

ds3-autogen-python/src/main/resources/tmpls/python/commands/all_commands.ftl
ds3-autogen-python/src/main/resources/tmpls/python/commands/static_classes.ftl
ds3-autogen-python/src/main/resources/tmpls/python/commands/types/parser_function.ftl

Updates to support Python 3 SDK work merged in https://github.com/SpectraLogic/ds3_python3_sdk/pull/42

PYTHONSDK-97: updating python templates for bug fixes.

---

ds3-autogen-java/src/main/java/com/spectralogic/ds3autogen/java/generators/requestmodels/MultiFileDeleteRequestGenerator.java
ds3-autogen-java/src/main/resources/tmpls/java/request/multi_file_delete_request_template.ftl
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/JavaFunctionalTests.java
ds3-autogen-java/src/test/java/com/spectralogic/ds3autogen/java/generators/requestmodels/MultiFileDeleteRequestGenerator_Test.java

Used to generate code for https://github.com/SpectraLogic/ds3_java_sdk/pull/593

Fix generation of Java MultiFileDeleteRequest to allow version ID to be specified.
